project_id = "laluxmwarlejdwyboudz"

[functions.sync-system-parameters]
verify_jwt = false

[functions.sync-wallet-kind-30889]
verify_jwt = false

[functions.batch-wallet-import-kind-30889]
verify_jwt = false

[functions.fetch-wallet-balance]
verify_jwt = false