project_id = "laluxmwarlejdwyboudz"

[functions.blockchain-monitor]
verify_jwt = false

[functions.sync-system-parameters]
verify_jwt = false

[functions.sync-wallet-kind-30889]
verify_jwt = false

[functions.fetch-wallet-balance]
verify_jwt = false

[functions.sync-profile-data]
verify_jwt = false

[functions.kind-87005-new-lana-registration]
verify_jwt = false

[functions.kind-cron-87003-monitoring-unregistered-coins]
verify_jwt = false

[functions.kind-cron-37772-lanaknight-registry]
verify_jwt = false
